### ISSUE TITLE
Plugin doesn't recalculate the colspan for the td.dataTables_empty row on resize

### ISSUE THREAD

**Issue by akkie** [DataTables/Responsive#100]
I have a table with x columns. In responsive mode three columns will be displayed. If the table is empty, then the row (td.dataTables_empty) gets a colspan from 3. Now if I resize the table, so that more columns will be displayed, the row keeps the initial colspan.

![dt-bug-3](https://user-images.githubusercontent.com/307006/28461135-83c23252-6e15-11e7-9a06-108242a4e655.png)
![dt-bug-full](https://user-images.githubusercontent.com/307006/28461139-865d6a22-6e15-11e7-8ca0-6cc94098add1.png)

https://jsfiddle.net/j58yxxtx/1/

**Comment by DataTables** [comment]
Hi,

Thanks for raising this. Its actually [already been fixed by this commit](https://github.com/DataTables/Responsive/commit/169a61c0b10883f32225630f4b7e6afafd9faa5b).

[Updated fiddle](https://jsfiddle.net/j58yxxtx/2/) using the nightly version.

**Comment by akkie** [comment]
Thanks for the response. Is there an ETA for a new release? I use the NPM version so I cannot use the nightly.

**Comment by DataTables** [comment]
I'll try to get it packaged up next week.
