### ISSUE TITLE
Some hidden columns displayed as  [object Object]

### ISSUE THREAD

**Issue by manutiedra** [DataTables/Responsive#104]
I don't know why some hidden columns are displayed as [object Object] when shown using the expand button. When the window size is big they are displayed properly. In the same table, other columns display fine.

I've tried it in Firefox, Chrome and Microsoft Edge and it happens in all of them.

This doesn't happen in all the datatables as I have been using them for a couple of weeks and it is the first time I've seend it. I have a live site where you can see the problem. Let me know how to pass you the credentials if you are interested in checking it out.

**Comment by DataTables** [comment]
Can you link to a page showing the issue please. allan @ the DataTables domain if you don't want to make the page public.

**Comment by manutiedra** [comment]
credentials sent

**Comment by manutiedra** [comment]
It turns out that for array types, the normal expanded state showed the values properly but when the values don't fit and the responsive extension kicks in, the values do not display properly if they are arrays. 

Changing the column "data" property from 'field_name' to 'field_name[, ]' makes it work.

Thank you for your help tracking the problem!

**Comment by nikhilroy2** [comment]
same issue, someone said, it's like it's trying to fetch from array not text base that's why.

**Comment by AllanJard** [comment]
@nikhilroy2  Can you link to a test case showing the issue so I can offer some help please?
