### ISSUE TITLE
Remove responsiveness sign from data table header. 

### ISSUE THREAD

**Issue by jaipundir** [DataTables/Responsive#106]
Hey Team,
I have used responsiveness feature of data table. I am using two level data table with responsiveness feature for both levels but I am getting responsiveness sign in the header of child grid as well. I want responsiveness sign only on the rows but not on the header text.Any help will be appreciated.
Thanks in advance

**Comment by DataTables** [comment]
Hi,

Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

**Comment by AllanJard** [comment]
No test case available to debug, so going to close.
