### ISSUE TITLE
Bootstrap 4 with .table-sm

### ISSUE THREAD

**Issue by marios88** [DataTables/Responsive#107]
Currently you have to set the class `compact` in order for the `(+)/(-)` to display properly but bootstrap 4 uses `table-sm`, so you have to set both

not a major issue, but a thing you have to remember!

**Comment by DataTables** [comment]
[This](https://github.com/DataTables/Responsive/commit/2e31c93763efe9374d6d2ab9d155bb3ea9beb58b) along with the other latest updates should address this :-).
