### ISSUE TITLE
responsive.details.type = '' doesn't work as expected

### ISSUE THREAD

**Issue by pajusmar** [DataTables/Responsive#108]
The [documentation example](https://datatables.net/extensions/responsive/examples/display-types/immediateShow.html) states that when the _responsive.details.type_ option is set to be an empty string it disables the user's ability to toggle the child rows - i.e. in this example the full contents of the table are always visible.

A click on a first cell of any row will hide the connected child row.

**Comment by DataTables** [comment]
Thanks for letting me know about this! The description was just plain wrong there I'm afraid. I've updated it now - `responsive.details.target` being an empty string is needed to disable the end user interaction. You'll probably need the code update for that as well.

**Comment by pajusmar** [comment]
Thanks for the quick response and fix!
