### ISSUE TITLE
Responsive doesn't adjust page navigation bar to fit to screen

### ISSUE THREAD

**Issue by hingston** [DataTables/Responsive#110]
Step 1: https://jsfiddle.net/q0p5yo2e/
Step 2: Adjust the column so the right side is 400px or less
Step 3: Click run

The adjust page navigation bar is too large and prevents the page from properly fitting on the screen. This is a problem for all mobile users and Google flags this as a mobile unfriendly page.

It could be fixed by displaying less page numbers.

Also posted here (oops): https://datatables.net/forums/discussion/52943/bug-responsive-doesnt-adjust-page-navigation-bar-to-fit-to-screen

**Comment by DataTables** [comment]
Thank you - I agree. The paging input is currently not responsive. That is something that needs to be addressed in DataTables core.

**Comment by AllanJard** [comment]
Responsive paging is a feature of DataTables 2 which will ship in the near future.
