### ISSUE TITLE
jQuery.fn.blur() event shorthand is deprecated

### ISSUE THREAD

**Issue by bytestream** [DataTables/Responsive#116]
> jQuery.fn.blur() event shorthand is deprecated

https://github.com/DataTables/Responsive/blob/2.2.3/js/dataTables.responsive.js#L672

### Fix:
Replace `.blur()` with `.trigger('blur')`

https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

`.trigger()` has been around since `1.0` so shouldn't be any compatibility issues. Ref: https://api.jquery.com/trigger/

**Comment by DataTables** [comment]
Thanks! Fixed here: https://github.com/DataTables/Responsive/commit/d2c060e2467c487bdb2d139449ee27d7005d133a .
