### ISSUE TITLE
Datatable Responsive not working when add Complex header 

### ISSUE THREAD

**Issue by Jayanta-Moharana** [DataTables/Responsive#118]
Please post support requests and questions in the DataTables forums at https://datatables.net/forums. Support requests posted here will be closed. The intention of this request is to allow all questions to be located in a single, searchable, location.

When you post your question in the DataTables forums, please ensure that you include a link to the page showing the issue so it can be debugged.

**Comment by AllanJard** [comment]
[Support for this committed here](https://github.com/DataTables/Responsive/commit/c0d11d2477f6dff19279a73d2f0ebb424c6a3635). Will ship as Responsive 3.
