### ISSUE TITLE
Responsive with + visible:false of target

### ISSUE THREAD

**Issue by xkpx64** [DataTables/Responsive#120]
As you can see in my post in datatables problem destroys datatable.
https://datatables.net/forums/discussion/68074/deeplinking-and-ellipsis-and-column-visibilty#latest

Live demo: http://live.datatables.net/ruwutute/15/edit?html,js,output ( uncomment // visible )

More digging shows that nowrap wrap starts the problem.

How can bypass this or fix it ?

**Comment by DataTables** [comment]
Let's continue the discussion in the forum, rather than having it in two places. I'll be replying there shortly.
