### ISSUE TITLE
support colspan in the footer

### ISSUE THREAD

**Issue by abbasmohamedeng** [DataTables/Responsive#123]
Is responsive plugin currently support colspan in the footer
I need to add custom search in footer
![Capture](https://user-images.githubusercontent.com/34089758/130047579-b587d14b-8fbd-4686-83b2-bbe1ca2c784d.PNG)

**Comment by AllanJard** [comment]
No - I'm afraid that it does not yet. DataTables 2 will feature the APIs to make this possible in this extension.

**Comment by AllanJard** [comment]
Support for this will be part of the Responsive 3 release alongside DataTables 2. [Commit here](https://github.com/DataTables/Responsive/commit/c0d11d2477f6dff19279a73d2f0ebb424c6a3635).
