### ISSUE TITLE
Responsive 3.0.3 adds a large, empty col into the table colgroup after table is destroyed/re-rendered

### ISSUE THREAD

**Issue by iluno90** [DataTables/Responsive#132]
I did some testing and it appears that if I revert to Responsive 3.0.0, 3.0.1, or 3.0.2, this issue does not occur.

Basically, I have a somewhat complex implementation which allows filters to be applied - when they are, the table will be destroyed/re-drawn (it might take a bit to make a test case if you need one). On 3.0.3, when I apply the filter, a new col is generated in the colgroup for the table, with a width roughly equal to the original table - it essentially creates a huge new column extending from the right of the table with a duplicate data-dt-column number (the screenshot is after applying a filter 3 times).

![duplicate_cols](https://github.com/user-attachments/assets/e085a354-bd80-4265-9261-615353005ad2)

Here is some of the code where my table is defined and generated, inside of a function which also runs when filters are applied. Originally I thought it may be related to my invisible column or the way the sorting priority is defined but I don't think that's the case because changing them or removing the invisible column didn't seem to change anything.
```
    table = $('#mytable').DataTable({
        "initComplete": function(settings, json) {
               //Just commented stuff
        },
        destroy: true,
        //Destroy so alternate arrays can be loaded on the fly into the table
        data: currentTableArray,
        pageLength: 20,
        //autoWidth: true,
        responsive: {
            details: false,
        },

        dom: 'rt<"table-footer container-fluid p-3 text-bg-light shadow-sm"<"container-xxl"<"row"<"d-none d-md-flex justify-content-start align-items-center col-md-4"l><"d-none col-lg-2 d-lg-flex justify-content-center align-items-center text-nowrap"i><"col-12 col-md-8 col-lg-6 justify-content-center justify-content-md-end d-flex"p>>>>',

        "columnDefs": [
            {
                className: "align-middle text-center",
                targets: [0, 3, 4, 1, 5, 6, 7, 8],
            },
            {
                className: "mb-0 text-nowrap",
                targets: 2
            },
            {
                className: "text-nowrap",
                targets: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
            },
            {
                responsivePriority: 1,
                targets: 0
            },
            {
                responsivePriority: 10010,
                targets: 4
            },
            {
                responsivePriority: 10009,
                targets: 9
            },
            {
                responsivePriority: 10008,
                targets: 5
            },
            {
                responsivePriority: 10007,
                targets: 6
            },
            {
                responsivePriority: 10006,
                targets: 7
            },
            {
                responsivePriority: 10005,
                targets: 2
            },
            { //Invisible, but searchable
                targets: 10,
                searchable: true,
                visible: false
            }
        ],
        order: [
            [9, 'desc'],
            [secondaryFilter, ascORdesc]
        ],

    });
```

**Comment by AllanJard** [comment]
Thanks for flagging this up. It is actually an error in DataTables core's `ready()` method. It uses an event handler which wasn't being unbound when the table was destroyed. Responsive makes use of that method, so the second time around its initialisation was called twice and the wheels came off!

[This commit](https://github.com/DataTables/DataTablesSrc/commit/a7e148ff64c424bed3d6e86e91494357a9afba7c) to DataTables core fixes the issue. It will be released as 2.1.7 probably next week.
