### ISSUE TITLE
Incorrect cloning of table

### ISSUE THREAD

**Issue by nickturner** [DataTables/Responsive#15]
When the table is cloned to get the minimum table sizes the header is incorrectly cloned resulting in the DOM hierarchy of  thead>th instead of thead >tr>th

The line

    var cells        = dt.columns().header().to$().clone( false ).wrapAll('tr').appendTo( clonedHeader );

need to be

    var classes      = dt.settings()[0].oClasses;
    var cells        = dt.columns().header().to$().clone( false );
    var row          = cells.wrapAll('<tr/>').parent().addClass(classes.sHeaderTR).appendTo( clonedHeader );

due to the way wrapAll() works

**Comment by DataTables** [comment]
Hi!

Sorry I didn't reply to this at the time :-(. The latest Responsive software [does something similar](https://github.com/DataTables/Responsive/blob/master/js/dataTables.responsive.js#L644) to what you suggest - reformatted to not use `$().wrapAll()` (I screwed its use up once already... :-) ).

Allan
