### ISSUE TITLE
Calculation to Determine Hidden Columns Seems Incorrect When Paging is Used

### ISSUE THREAD

**Issue by ComputerTinker** [DataTables/Responsive#17]
I have a table consisting of several dozen rows, and currently have my paging option set for 10 rows per page.  It seems as though the responsive extension is calculating which columns to show and which to hide based on the first 10 rows being displayed.  When I page to to the next 10 rows (which contain some longer text), the table consistently extends past the end of the web page, even after resizing the browser window several times.  

I created a button on my page which did:

``` javascript
  hQotHstry.columns.adjust();
  hQotHstry.responsive.recalc();
```

but after browsing to the second page of rows and clicking that button, the result was the same.  Here's a live example:  http://jsfiddle.net/69b4nnqx/1/

Any help appreciated.  Thank you!

**Comment by Philzen** [comment]
> Ideally Responsive would use the data from all pages

imho responsive would ideally use the data that is actually (currently) being displayed, wouldn't it?

> Calling those functions on the page event perhaps..

sounds like a stable interim fix to me, at least until somebody comes up with a better approach. However, in my current problem scenario (server-driven, data for other pages than the current one is fetched via Ajax) the call to `columns.adjust()` is not needed. 

My workaround looks as follows: 
``` js
var config = { ... },
    $dataTable = $('#myTable').dataTable(config);

$dataTable.on('page.dt', function (e, settings) {
    $dataTable.one('draw.dt', function (e, o) {
        dtObj.api().responsive.recalc();                    
    });
});
```

Would be good to get the responsive extension to hook into those events "under the hood" ;)

**Comment by DataTables** [comment]
Can you give me a link to a page where this is causing issues please? My concern about doing a full recalculation is that it is really not good for performance, so I'd like to understand the table that is causing this issue.

**Comment by AllanJard** [comment]
Really old issue this with no test case. I think the current calculations are correct. Going to close.
