### ISSUE TITLE
Unresponsive Column Headers

### ISSUE THREAD

**Issue by Gallopaway** [DataTables/Responsive#18]
Think i have found an issue, if you set the srollY property it seems to break the responsive behaviour of the column headers as in the headers stay the same width where the column widths change.
$(#example).DataTable({
  scrollY: "200px"
});

I have attached a screenshot 

JSFIDDLE http://jsfiddle.net/Gallopaway/y7c0b6Lf/1/

![datatable header](https://cloud.githubusercontent.com/assets/7976401/5357507/219fb63a-7fb1-11e4-95e3-31cda95d9f01.JPG)

**Comment by DataTables** [comment]
Sorry I didn't reply to this at the time!

The example you link to doesn't actually use the software in this repo. However, I've just added an example which shows it being used with the DataTables scrolling option which works well, so I'll close this issue.
