### ISSUE TITLE
Columns do not smoothly collapse on browser resize in bootstrap

### ISSUE THREAD

**Issue by NYPD** [DataTables/Responsive#20]
Hello, I'm not sure if this is a bug or just a mistake on my part, but I ran into an issue where the columns on the datatable do not nicely collapse/show on browser re-size. The issue can be found here: [Fiddle](http://jsfiddle.net/hdnquzk4/5/)

You can see when re-sizing the "results" windows the columns overflow a bit before Responsive takes over.

However, when debugging I found a really hacky solution. Essentially I have to enable white-space:no-wrap on the tables td's and th's and then immediately reset the white-space css style to normal afterwards using jQuery. This solution can be found here:  [Fiddle](http://jsfiddle.net/hdnquzk4/4/)

This could be a browser bug but I tried both the latest version of Chrome and Firefox and see the same issue. Or I'm just simply messing up the declaration.

**Comment by ertogs** [comment]
I am having the same problem. Not sure but it seems the width of the column headline causes this problem.

**Comment by NYPD** [comment]
It seems:https://github.com/DataTables/DataTables/issues/455 has fixed this issue. Updated jsFiddle to show fix: http://jsfiddle.net/hdnquzk4/11/

Thanks a bunch!

**Comment by DataTables** [comment]
Nice one. Thanks for updating this issue!

**Comment by ertogs** [comment]
Thank you!

**Comment by JeremyDa** [comment]
table.dataTable th,table.dataTable td {
            white-space: nowrap;
        }
 fixed my issue
