### ISSUE TITLE
Add method to recalculate breakpoint logic

### ISSUE THREAD

**Issue by DataTables** [DataTables/Responsive#21]
As suggested by @cdaringe in #8 there needs to be an API method that will allow the column logic to be recalculated when class names change through external interaction.

**Comment by cdaringe** [comment]
Did I make a remark just hours ago and already already see the feature get built in?
You sir, are a man of the people!
Can't wait to try!
![](http://i626.photobucket.com/albums/tt344/JHnGA09/Misc/GenieJawDropping.jpg)

**Comment by DataTables** [comment]
Just wish I could do them all as quickly!

But the best bit is that I love that film - thanks for the image. Great end to the day!

**Comment by cdaringe** [comment]
By the way, worked great!  Thanks again.
