### ISSUE TITLE
 The Responsive extension can't work with the datatables rendered with javascript soured data

### ISSUE THREAD

**Issue by libillgithub** [DataTables/Responsive#23]
The Responsive extension can't work with the datatables rendered with javascript soured data.

**Comment by DataTables** [comment]
Please link to a test case showing the issue. It should work just fine as the mechanism is the same as for [ajax sourced data](http://datatables.net/extensions/responsive/examples/initialisation/ajax.html).

Allan

**Comment by cdaringe** [comment]
I use this regularly.  This is not a bug (1.10.4 & 1.10.5 @least).  Should be closed.  @libillgithub, put up a fiddle and I can help you out if allan is slammed.

**Comment by DataTables** [comment]
No test case provided - closing.
