### ISSUE TITLE
Use of "responsive.details" with "columns" options

### ISSUE THREAD

**Issue by xavierfaucon** [DataTables/Responsive#24]
Hello,

First of all thank you for the great job you're doing on this library, it's impressive to see such an exhaustive work.

I've done some testing with Datatables 1.10.* + BS3 Integration + Responsive and I don't see any solution to this case:

http://jsfiddle.net/qj1507ny/2/

How would you define a control column when you already use the "columns" options?
It is linked with this example: https://datatables.net/extensions/responsive/examples/child-rows/column-control.html

**Comment by DataTables** [comment]
The `columns` array length _must_ be the same as the number of columns in the table. So if you want an additional column, you would need to define it in that array. Is that not possible in your case?

**Comment by xavierfaucon** [comment]
Hello,

Ok for column length but I can't define the first column with:
`"data": null`
or
`"data": ""`

Demo: http://jsfiddle.net/qj1507ny/6/

Expected behavior for the `control` class should be to have an empty first column with the "+" symbol no :-) ?

**Comment by DataTables** [comment]
Use the `defaultContent` parameter if you want 'null' data: http://jsfiddle.net/qj1507ny/7/ . Docs: http://datatables.net/reference/option/columns.defaultContent .
