### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Responsive' of undefined

### ISSUE THREAD

**Issue by yameenyasin** [DataTables/Responsive#25]
I am getting this Error for the bewlo piece of code:
else if ( jQuery && !jQuery.fn.dataTable.Responsive ) {
	// Otherwise simply initialise as normal, stopping multiple evaluation
	factory( jQuery, jQuery.fn.dataTable );
}

**Comment by DataTables** [comment]
Please link to a test case showing the issue.

**Comment by yameenyasin** [comment]
![responssiveerror](https://cloud.githubusercontent.com/assets/6688507/6125175/6b62b718-b139-11e4-9c92-71dd6de31c5c.png) Please refer to this screen shot.

Earlier I was using the the script from the following CDN https://cdn.datatables.net/responsive/1.0.3/js/dataTables.responsive.min.js

But I found that there was issue with the responsiveness as it was breaking on some widths where the table was overflowing out from the div. Then I found that you have fixed it. I just replaced the existing JS with this new JS where I am getting the attached Error

**Comment by DataTables** [comment]
I need a link to a test page showing the issue please as I can't debug the problem at the moment. You can use JSFiddle or CodePen if you can't give me a direct link.

**Comment by yameenyasin** [comment]
I found the problem. My main script dataTable.JS was loading late as i am using it on cloud.
Thanks for the Fix. Really aprreciate..
