### ISSUE TITLE
Issue when hidden fields length is greater. They do not auto adjust to the parent div width, instead the <table> overflows from the outer <div> 

### ISSUE THREAD

**Issue by yameenyasin** [DataTables/Responsive#26]
I have a test table with lengthy column names and values. When the page loads the responsiveness is perfect. But when i select any row and expand the rest of the hidden columns which are little lengthier in size, they do not wrap themselves automatically. Instead the length of the TD increases which inturn increases the length of the entire table and hence the table overflows out of the DIV.
Suggestion:
We can wrap the UL within the DIV with overflow-x:scroll, or we have to think of wrapping the contents of the UL to auto adjust to next line if content width is much greater.

Please refer to the attached screenshot.
![ui-bug](https://cloud.githubusercontent.com/assets/6688507/6128352/018a1a44-b15b-11e4-8fb1-d623446e3b44.png)

**Comment by DataTables** [comment]
Can you please link to a test case showing the issue so it can be debugged.

**Comment by yameenyasin** [comment]
I have mentioned the scenario .. Please refer to the attached screenshot for reference and better understanding of this issue
Thanks

**Comment by DataTables** [comment]
A test case would greatly help debugging the issue. Without a test case I will need to find time to create one and I can't say when that will be - likely no soon due to other commitments.

**Comment by yameenyasin** [comment]
I will try to create a fiddle. Give me some time.

**Comment by yameenyasin** [comment]
https://jsfiddle.net/YameenYasin/e1vsrLpq/

**Comment by Braunson** [comment]
Having a smiliar issue but with the parent table width not becoming fitting, on a mobile view it's ~680px wide, I tried adding width="100%" to the table which fixes the width issue (as DataTables is setting it regardless of my:

```javascript
$('.dataTable').dataTable({ 
    responsive:true,
    "autoWidth": false,
    "bAutoWidth":false
});
```

but then the responsiveness (i.e. the green +, hiding rows, etc) stops working entirely.

**Comment by yameenyasin** [comment]
@DataTables  Do we have any updates for this issue ?

**Comment by DataTables** [comment]
Not yet sorry. Its on my todo list.

**Comment by yameenyasin** [comment]
Ok Thanks :)

**Comment by DataTables** [comment]
Updated fiddle with the fix: https://jsfiddle.net/e1vsrLpq/1/ .

Also you had the following the CSS:

```
   table.dataTable th,
    table.dataTable td {
        white-space: nowrap;
    }
```

So I had to add:

```
    table.dataTable li {
        white-space: normal;    
    }
```

**Comment by Braunson** [comment]
Implemented this but receiving this issue (notice the heading has a large 680px width)
![issue](https://cloud.githubusercontent.com/assets/577273/6237900/a5270c66-b6c4-11e4-97e9-222fdd6dc602.PNG)

**Comment by DataTables** [comment]
Can you link to an updated test case showing the issue please.

**Comment by Braunson** [comment]
@DataTables Sorry, had issues with jsFiddle -- http://dev.geekybeaver.ca/example/

**Comment by DataTables** [comment]
Thanks for the link. It doesn't appear to relate to the original issue at all so I've created #27. Things are busy here at the moment so I can't say when I'll get to look at it, but I'll try to as soon as I can.

**Comment by yameenyasin** [comment]
Thank you @DataTables  for the fix. :)
