### ISSUE TITLE
Responsive - CSS Inheritance - DataTables, with (normal) table as value

### ISSUE THREAD

**Issue by DerDu** [DataTables/Responsive#29]
If I use a 'normal' table (only html5, no datatable added) as value of a 'responsive' datatable, then the handler (to display details) is added to all 'normal' table within the 'responsive' datatable (css only, not events) instead of appearing only in first column of the 'responsive' datatable

e.g.
![unbenannt](https://cloud.githubusercontent.com/assets/616953/6277670/e9ee88a6-b890-11e4-805f-bafc27525865.png)

(1.10.4)

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please? The CSS classes used for Responsive are applied only to tables which have the `dataTable` class: https://github.com/DataTables/Responsive/blob/master/css/dataTables.responsive.scss#L31 .

**Comment by DerDu** [comment]
of cource ;-), here you go http://jsfiddle.net/2snkn4xr/

the classes are applied to table.dataTable - correct, but because of inheritance they are also applying styles to e.g. td and th of children inside the target table.dataTable (which should be restricted to direct descendant of table.dataTable)

**Comment by DataTables** [comment]
Ah I see - thanks for the test case! I totally misunderstood the problem!

Fixed now - updated Fiddle here: http://jsfiddle.net/2snkn4xr/1/ .

**Comment by DerDu** [comment]
In your updated test case there is still an issue 

If you open the details the style for closing gets still inherited ;-)

**Comment by DataTables** [comment]
Doh! Updated fiddle with a full fix: http://jsfiddle.net/2snkn4xr/2/ .

**Comment by DerDu** [comment]
Now everything seems to be ok :-) 
Thx for the fix ;-)
