### ISSUE TITLE
Init event listener breaks other plugins

### ISSUE THREAD

**Issue by texttechne** [DataTables/Responsive#30]
There's a global event listener which will produce an error whenever an event with name "init" is triggered. The offending code is to be found here:  
https://github.com/DataTables/Responsive/blob/master/js/dataTables.responsive.js#L815

```javascript
$(document).on( 'init.dt.dtr', function (e, settings, json) {
    if ( $(settings.nTable).hasClass( 'responsive' ) ||
         $(settings.nTable).hasClass( 'dt-responsive' ) ||
         settings.oInit.responsive ||  // ERROR
         DataTable.defaults.responsive
       ) {
    ...
}) 
```

If the **init** event is triggered by a different plugin (slick slider in our case), then *settings.oInit* will be undefined and hence an error occurs. In our case dataTables library is included but no table is initialized.

Maybe a misconception of JQuery's event namespacing?  However, either some kind of guard clause should be used in the function body (checking the namespace?) or a more specific event than **init** is needed.

**Comment by DataTables** [comment]
Right enough: http://live.datatables.net/yafopupe/1/edit .

I thought that the event listener attached would only be triggered if the event itself was triggered with the `dt` namespace... Looks like I'm mistaken and back to the jQuery documentation.
