### ISSUE TITLE
Cannot Destroy A Responsive Table with The Responsive Row Open

### ISSUE THREAD

**Issue by cdaringe** [DataTables/Responsive#31]
Example:

1. visit http://jsfiddle.net/1z7cv8we/1/
1. open a responsive row
1. click the destroy button. observe the error in the console.

Hopefully that's an easy one to fix!

**Comment by DataTables** [comment]
Yup - super easy. Just use the latest versions of DataTables and Responsive: http://jsfiddle.net/1z7cv8we/2/ :-)

**Comment by cdaringe** [comment]
Man, **you rock!**
