### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by cdaringe** [DataTables/Responsive#32]
Hi Allan:

Good afternoon.  In some of my designs, I've had to disable `responsive` because of performance reasons.  Example, when I have ~5+ cols and 1000-3000 rows. Filtering, for instance, really chokes up on each keystroke.  Even with `deferRender` enabled (`data` mode, not true `ajax` mode) or filter text that doesn't change the resulting set, the browser hangs as DT chugs.  It took me a while to isolate it to responsive, as I didn't think it would be a likely candidate.  Post-removal, my tables come right back to life.

FYI and thanks!

Chris

**Comment by DataTables** [comment]
Hi Chris,

Have you tried the nightly version (i.e. the latest code in this repo rather than the last release)? There are some performance improvements in that.

**Comment by cdaringe** [comment]
Hey Allan,

I haven't had a chance to try it yet.  So busy :$  You're the man.  I'll try it out out sometime in the next couple weeks and hopefully come back and update this thread!
