### ISSUE TITLE
If using column details type, it is possible for only control column to show

### ISSUE THREAD

**Issue by SpliceVW** [DataTables/Responsive#33]
Assume the following:
* `responsive.details.type` is set to `column`
* the first column of data will not fit in the viewport (e.g. has long words)

In this circumstance, only the control column is shown. It would seem preferable for the table to overflow the page than have no data column shown, as there is no identifying information for each row.

This is not an issue when `responsive.details.type` is set to `inline` because the control element is within the first column.

**Comment by DataTables** [comment]
Interesting. Thanks for flagging this up - I'll need to have a think about the correct thing to do here and how to fix it. I'm a bit overwhelmed with bugs and support at the moment, so can't say when exactly that will be, but I will get to it :-)

**Comment by DataTables** [comment]
I'm afraid that at the moment I don't think I'm going to put this into place (although I might change my mind). This is based on discussions with other users of Responsive that never want the table to overflow (that is the point of Responsive after all).

I'm going to close this one for now, but I will come back to it if others flag it up as well.
