### ISSUE TITLE
Doesn't take into account the column.visible

### ISSUE THREAD

**Issue by Belphemur** [DataTables/Responsive#34]
If you chose to hide some columns like in the initialization of the DataTable, responsive doesn't follow the directive.

It would be nice that the setting visible:false get translated into className: never

**Comment by DataTables** [comment]
Hi,

Thanks for the feedback. There is a discussion about that here: https://datatables.net/forums/discussion/22700 , among others.

Responsive and column visibility needs better integration for certain, but at the moment it is operating as intended, and there other discussions about this issue in the forums, so I'm going to close this issue for now.
