### ISSUE TITLE
Forgotten console.log in 1.0.5

### ISSUE THREAD

**Issue by gdurelle** [DataTables/Responsive#36]
Nothing serious but a bit tedious.

You forgotten a console.log in the 1.0.5 released version.

Awesome lib anyway :)

**Comment by DataTables** [comment]
Yes, very annnoying! I felt like a right idiot when I realised :-(.

[Committed the fix](https://github.com/DataTables/Responsive/commit/09371e22e66a2c43) as soon as I had realised, so the code in the repo doesn't have this issue. I will be releasing 1.0.6 with the fix soon.
