### ISSUE TITLE
Vertical scrolling exception in example page

### ISSUE THREAD

**Issue by aaronmars** [DataTables/Responsive#41]
When a datatables instance is run with the responsive plugin and Vertical scrolling, an exception is showing up when new columns need to be shown as a result of the table getting wider.  It is visible on the following example page:
https://datatables.net/extensions/responsive/examples/styling/scrolling.html

Start with a refreshed page at width 412px, and widen the example to around 460.
At this point, the "Position" column should become visible.  In the dev console, the exception is shown.
This occurs in _fnCalculateColumnWidths(), and looks like it is due to the cells in the header table not being in-sync with the hidden header cells.

Following the repro steps above, you'll be able to see the thead under the .dataTables_scrollHead has 3 header colums, but the thead under the .dataTables_scrollBody only has 2 (the tbody here is set up for 3).  The exception occurs when the style is being set on this 3rd header which is missing from the hidden thead.

This is reproducible with:
jquery 1.11.1 and 1.11.3
dataTables 1.10.7
dataTables.responsive 1.0.6

**Comment by DataTables** [comment]
> dataTables 1.10.7

This is the problem. There is a bug in 1.10.7 unfortunately. The [1.10.8-dev nightly](http://datatables.net/download/index#DataTables) fixes this. 1.10.8 will be released in the next few weeks.
