### ISSUE TITLE
Doubling the click event in the show details button

### ISSUE THREAD

**Issue by mauriciohimaker** [DataTables/Responsive#43]
Prior to Line 442 of the dataTables.responsavel.js Files added this line:

$(dt.table().body() ).off('click'); 

Because it could happen to add More Than Once the event just the Show button the columns Details que Were hidden , and so duplicate information .

**Comment by DataTables** [comment]
This is an event inside the responsive row's details that is causing the issue right? If so, I would say that the click event that has been added when the child row was shown should be likewise removed when the row is hidden. It isn't Responsive's responsibility to remove events that have been added externally.

If I've misunderstood, please feel free to reopen with a link to a test case.
