### ISSUE TITLE
No generated css file in the repository

### ISSUE THREAD

**Issue by Haixing-Hu** [DataTables/Responsive#44]
Hi,  
I use the bower to manage all third part packages. But I found that the bower package of `datatables-
responsive` does not contain a generated css file. It only contains scss files. 

Of couse I can generate the css file manually, but it is not convenient to manually generate css files each time the package got updated.

So could you please provide a generated css file in the bower package? 

Thank you in advance.

**Comment by DataTables** [comment]
Thanks for posting this. My plan is to introduce new distribution repositories which will mirror this one, but contain the distribution files, suitable for each of the styling libraries that are supported.

I hope to get that done later this month.

**Comment by Haixing-Hu** [comment]
OK, I see. Thanks a lot.
