### ISSUE TITLE
Does 1.0.7 exclude CSS files intentionally?

### ISSUE THREAD

**Issue by anavarro9731** [DataTables/Responsive#45]
I only see the SASS file in the CSS directory now?

**Comment by DataTables** [comment]
Hi - I'm going to use this repo as a source repo and create distribution repos for the built files. That will probably happen sometime next week.

**Comment by althaus** [comment]
Ahh... that just broke my update. :/

**Comment by gbuuss** [comment]
I work with bower and also it broke my update!! :(

**Comment by svassaux** [comment]
yes, this is bad, css files should be included. thanks

**Comment by Philzen** [comment]
Any updates on the distribution repos?

1.0.7 also broke in my bower setup...

**Comment by DataTables** [comment]
Probably next week. This only if everything goes smoothly, and we all know how likely that is :-)

**Comment by rhyudek1** [comment]
I really need css files, please put them back. :crying_cat_face:

**Comment by lpetre** [comment]
It is very frustrating for a patch release to break backwards compatibility. Anyone using tilde rules (the npm default) to include this bower package and relied on the files as they existed in 1.0.6 could be broken by this change.

**Comment by DataTables** [comment]
Please accept my apologies. I was basing version numbers on the software only, but that in retrospect is an error. It should of course be based on the packing as well. I'm going to be starting work on the distribution repos this afternoon.

**Comment by rhyudek1** [comment]
anything new?

**Comment by DataTables** [comment]
I am in the process of fixing this just now. It is taking a while to get everything correctly set up. I woill post back here when it is done. Hopefully in the next couple of days.

**Comment by TCB13** [comment]
+1 on this guys!

**Comment by DataTables** [comment]
Couple of days was optimistic... Having problems getting the RequireJS aspect sorted out. Anyone with experience enough with RequireJS to help out - [your input would be very much appreciated](https://www.datatables.net/forums/discussion/31043).

**Comment by DataTables** [comment]
NPM and Bower packages are DataTables and its extensions (including Responsive) are [available now](http://datatables.net/blog/2015-11-09). There is a small packaging bug with Bootstrap for Responsive 2.0.0 which will be addressed with the 2.0.1 release coming up early next week.

**Comment by althaus** [comment]
Awesome! Thanks, @DataTables :+1:
