### ISSUE TITLE
table.responsive.rebuild() IE8 issue

### ISSUE THREAD

**Issue by SHRIVES23** [DataTables/Responsive#47]
I have checkboxes toggling certain columns on and off in a responsive datatable. Anytime I call table.responsive.rebuild() in IE8 it breaks the child rows from being allowed to be clicked in IE8. On page load they work fine, not until the table.responsive.rebuild is called does it break child rows from showing on click in IE8...

var checkboxes = function () {
        $('input[name="Checkboxes"]').click(function () {
            var table = $("#searchResults").DataTable();
            var attr = $(this).attr("data-header");

```
        if ($(this).is(":checked")) {
            $(table.columns('.' + attr).header()).removeClass('never');
        }
        else {
            $(table.columns('.' + attr).header()).addClass('never');
        };

        table.responsive.rebuild();
        table.responsive.recalc();
    });
}
```

**Comment by DataTables** [comment]
Can you link to a page showing the issue so it can be debugged please.

**Comment by SHRIVES23** [comment]
JSFiddle is having an IE8 issue...here's the link with code...

https://jsfiddle.net/4jd140xc/

**Comment by DataTables** [comment]
Thanks - it will be a little while (a few weeks probably) before I get a chance to set up an individual page to debug IE8. I'll post back here once I have had a chance to do so.

**Comment by AllanJard** [comment]
IE8 no longer supported - closing.
