### ISSUE TITLE
Missing js file in "Dist-DataTables-Responsive-Bootstrap#1.0.7"

### ISSUE THREAD

**Issue by larvanitis** [DataTables/Responsive#51]
Probably your build scripts are based on your master branch, which includes the new style scripts.

1.0.7 should only include the css in `bower.json` etc.

**Comment by DataTables** [comment]
Hi - yes - this is in error.

The Dist- packages aren't quite ready yet - it is something that I'm actively working on, but I didn't see a way of building the bower packages without making them public. Its taking a little bit of time to build them up.

I don't actually expect that tagged versions of the packages to currently work - they will need the next tagged release which will happen next week.

**Comment by larvanitis** [comment]
Awesome!

**Comment by dunnington** [comment]
This appears to be a problem with the 2.0.0 release as well. The bower.json file lists `js/responsive.bootstrap.js` but the repo has no `js` folder. I noticed [this](https://www.datatables.net/forums/discussion/31043) forum post about `requirejs` from a few weeks ago, so I assume the build scripts are still being tweaked? FWIW, as long as the `bower.json` file properly lists all the necessary assets for a package in it's `main` configuration, including CSS and JS assets for a package is pretty easy (I use the `grunt-bower` and `cssmin` plugins in my builds), so trying to include both via `requirejs` is unnecessary.

**Comment by DataTables** [comment]
Yeah - I screwed that up - sorry. I had thought I'd fixed it since, but it looks not. I'll post back here when I really have fixed it.

**Comment by DataTables** [comment]
[Its in now](https://github.com/DataTables/Dist-DataTables-Responsive-Bootstrap) but not yet released.

Because of this packaging error the next release likely won't be far away.

**Comment by dunnington** [comment]
Fantastic, thanks for the quick response!

**Comment by mello151** [comment]
Any new updates on this? I'm trying to decide if I should just go with a work-around or keep waiting on the update to the distribution.

**Comment by DataTables** [comment]
Not yet. Support has been taking about 99% of my time recently, so I've not had a chance to do any proper development.

**Comment by mello151** [comment]
I hear ya. No worries. Thanks for the quick reply.

**Comment by DataTables** [comment]
Wrapping up for the next release. This is fixed and will be included in Responsive 2.0.1 which I expect to publish at the start of next week.
