### ISSUE TITLE
Feature Request: Class to Hide Column From Detail/Child View Only

### ISSUE THREAD

**Issue by joelcdoyle** [DataTables/Responsive#52]
I have a column that I want to appear in `mobile-l` and `mobile-p` breakpoints, and not be visible on `tablet-l`, `tablet-p`, and `desktop` breakpoints (working properly). 

However, I also want the column NOT to appear in the details/child row of any breakpoint. Is this only achievable with the `renderer` option?

Summary: Never show in detail/child row, visible as column in `max-mobile`

**Comment by DataTables** [comment]
Yes this is correct - only the `renderer` option can be used to achieve this. If a column can be shown / hidden by Responsive, then it will be shown in the child row.

On the plus side, writing a custom renderer in the next version of Responsive will be much easier than it currently is. Hoping to have it released and documented next week.
