### ISSUE TITLE
Collision between responsive and buttons colvis 

### ISSUE THREAD

**Issue by majksner** [DataTables/Responsive#54]
`stateSave: true` doesn't work if both plugins are used. 

https://www.datatables.net/forums/discussion/28903/column-visible-state-save

**Comment by DataTables** [comment]
Correct - Responsive 1.x is not compatible with DataTables' column visibility. See the [compatibility table](http://datatables.net/download/compatibility).

This will be resolved in Responsive 2 and that code is in this repo if you want to try it out.

**Comment by majksner** [comment]
I'm using master branch for both Responsive and Buttons and I'm not sure if this a issue or it's normal behavior. If I have hidden columns in table using ColVis button, and while I'm on the full screen those hidden columns will not be visible when clicking plus button in the first column.

**Comment by DataTables** [comment]
That sounds correct - if the column is hidden using Button's column visibility controls, then with Responsive v2 the column won't be shown (since it has been hidden).
