### ISSUE TITLE
Column priority data attribute has no effect

### ISSUE THREAD

**Issue by sargue** [DataTables/Responsive#57]
Using the official JSBin and adding a `data-priority="1"` to the last column the expected result is that column should be always visible. It is not.

http://live.datatables.net/jobidiki/1/

**Comment by DataTables** [comment]
Got it right the second time around...

Updated example which uses the nightly built: http://live.datatables.net/jobidiki/2/edit .

Thanks for flagging this up!

**Comment by sargue** [comment]
You're welcome, thanks for the fast fix!

**Comment by downhiller** [comment]
Isn't the referenced "Updated example" even MORE broken?  It doesn't exhibit any "responsive" behaviour at all on my screen? All the columns are there, there's a horizontal scrollbar, and the green plus signs are missing.

**Comment by downhiller** [comment]
Scratch that, I think it's just that the "run with JS" button needed to be clicked (when it hadn't needed to be on the first one for some reason).

At least I can stop pulling my hair out over the 2 hours I've been trying to get data-priority to work on my own system now!
