### ISSUE TITLE
Responsiveness not working correctly after adding rows dynamically

### ISSUE THREAD

**Issue by Tklaversma** [DataTables/Responsive#58]
Hi Allan,

As you state [here](https://datatables.net/forums/discussion/24414/how-can-i-add-new-row-dynamically-in-responsive-table), adding a row dynamically to a responsive DataTable works the same way as adding it to a non-responsive DataTable; using ```row.add()```.
For some reason, this is not working as shown [here](http://jsfiddle.net/4pry7og5/82/). Am I doing something wrong or is it broken?

Besides my findings written above, I do got a working example on my current project with using ```ajax``` to add ```<td>```'s to the table and then call ```table.columns.adjust().draw()``` in the end. Unfortunately in this case, when rows are added dynamically, the responsiveness of the DataTable isn't working correctly.

Here you will find a [non-working example](http://pasteboard.co/23HAsMvD.png). You can see on the right side that a column is still half visible, instead of added to the dropdown (+).
Here you will find a [working example](http://pasteboard.co/23HyHKMS.png). You can see that all columsn that don't fit are added to the dropdown (+).

Hope you can help me out..

TK

**Comment by DataTables** [comment]
Thanks for posting this. It might be a while before I can look into it in detail. Got a blacklog of support requests just now.

**Comment by Tklaversma** [comment]
No problem. In the mean time I'll look for myself as well. If I find a/the solution, I'll update this post.

**Comment by DataTables** [comment]
I suspect that this might have been an issue in the DataTables API. However, using the latest code for both DataTables and Responsive has it working as expected: http://jsfiddle.net/4pry7og5/159/ .

**Comment by Tklaversma** [comment]
Awesome!! All seem to work correctly now. When can we expect the dev versions to be published (datatables 1.10.11 and Responsive 2.0.1)?

**Comment by DataTables** [comment]
Responsive 2.0.1 next week, but DataTables will likely be early next month.

**Comment by Tklaversma** [comment]
Ok, just implemented the new Responsive and DataTables and all works just find now.

Thanks!

**Comment by DataTables** [comment]
Can you open a new issue in the [forums](//datatables.net/forums) with a link to a test case showing the issue.

**Comment by iyilm4z** [comment]
I will try to open. But does anyone has an idea why this happens?

**Comment by iyilm4z** [comment]
Here is the code reproduces my case.
https://jsfiddle.net/q74axjfm/4/
