### ISSUE TITLE
Responsive hides colspaned footer

### ISSUE THREAD

**Issue by althaus** [DataTables/Responsive#59]
Hey,

I've stumbled upon an issue with our DataTables setup when activating responsiveness. We've got a table with x columns and a `tfoot` containing a single `<td colspan="x">`. So far so standard. Now we're using responsive with mode  `childRow` and the detail toggle gets added through an additional column added to the end of the regular columns.

```
options.responsive = {
    details: {
        type: 'column',
        target: -1
    }
};
```

This setup now leads to the situation that the single cell in the footer gets hidden by the responsive mode, too. Is there a way to exlude the footer from that/any handling? It should just sit there with its colspan in all its glory.

It was working well before the 2.0 update.

Cheers
Matthias

**Comment by DataTables** [comment]
Hi,

Unfortunately yes, Responsive 2.0 does not currently support colspan in the header or footer. This is because it no longer uses DataTables' own column visibility API to show / hide columns.

The plan is to reintroduce this feature for 2.1.

**Comment by althaus** [comment]
OK... thanks Allan for the clarification. I'm enforcing the visibility through CSS as a workaround for now.

**Comment by AllanJard** [comment]
colspan / rowspan and multi-row header and footers support was [recently added](https://github.com/DataTables/Responsive/commit/c0d11d2477f6dff19279a73d2f0ebb424c6a3635) and will ship in Responsive 3 alongside DataTables 2.
