### ISSUE TITLE
_detailsDisplay fails with details=false

### ISSUE THREAD

**Issue by jmcarp** [DataTables/Responsive#61]
The `detailsDisplay` method calls `this.c.details.display(...)`, which fails when the data table is invoked with `responsive: {details: false}`: "Uncaught TypeError: this.c.details.display is not a function". Is this option still supported?

**Comment by DataTables** [comment]
Sorry - that was a bug in 2.0.0. Corrected now and will be released in 2.0.1 which I don't expect to be too far away.

**Comment by jmcarp** [comment]
Thanks!

**Comment by procmail** [comment]
Just came across this bug as well. Awaiting 2.0.1. Any updates on when it'll arrive?

**Comment by DataTables** [comment]
Not yet. Support has been taking about 99% of my time recently, so no chance to do any development.

**Comment by Puresoft** [comment]
I also got this error now,...is there a workaround until 2.0.1 is released ?

**Comment by DataTables** [comment]
Yes - use the nightly version from this repo.

**Comment by Puresoft** [comment]
mmm, but I use the packed version,...I've used the download builder.

**Comment by DataTables** [comment]
You need to wait for the next release if you don't want to use the nightly. It will be available later this week.

**Comment by Puresoft** [comment]
Thanks, then I'll wait for the next release

**Comment by rootwalla** [comment]
ver 2.0.1 has a bug.
Ln199: if ( details.type !== false ) {
should be: if ( details !== false ) {

**Comment by DataTables** [comment]
Fixed in 6060cef6d0d89b1e4e65f110f3ed20288a58a87b. Thanks for letting me know about that.

The work around for now is to not use `responsive.details` as a boolean value.

**Comment by dougajmcdonald** [comment]
If we don't use responsive.details as a boolean, how do we tell responsive not to display child rows? Id I remove that and try perhaps:

`                    details: {
                        display: () => { return undefined; }
                    }`

or similar, I get the '+' button which in my case I don't want.

**Comment by DataTables** [comment]
Why wouldn't you use `responsive.details` as a boolean? If you don't want the details, surly that is the right thing to do?

**Comment by dougajmcdonald** [comment]
Because you said: 

> The work around for now is to not use responsive.details as a boolean value.

**Comment by DataTables** [comment]
Oh I see :-). The fix discussed above is in 2.0.2 which is the current release, so you could just use that?

**Comment by dougajmcdonald** [comment]
I expect so, although I had been using the NuGet package which I think is at version 1.10.10.

Would you advise using the latest GitHub release in general? it's a bit annoying to need to manually acquire it each time but I can handle that if it's going to keep me up to date more effectively :)

**Comment by DataTables** [comment]
The Nuget packages aren't maintained by myself, so I'm afraid I can't offer much help there (I have been thinking I should probably start offering "official" Nuget packages now that I've finally got NPM and Bower sorted out though - its just a question of getting the time to do it!).

So yes, either grab the release from GitHub, the DataTables site or NPM.
