### ISSUE TITLE
DataTables with Responsive + scrollY Issue

### ISSUE THREAD

**Issue by djuba** [DataTables/Responsive#62]
http://jsfiddle.net/uonhekd8/1/

Bootstrap 3.3.5, DataTables 1.10.10, FixedHeader 3.1.0, Responsive 2.0.0

When you run the above jsFiddle, the DataTables scrollHead columns do not line up with the scrollBody columns on initial load. This is much more visually apparent if you run the jsFiddle when the window is small enough to have a collapsed column, but is still an issue without collapsed columns.  If you resize the window, the columns will line up.

Any ideas on a short term quick fix I can implement?

Keep up the good work!

**Comment by djuba** [comment]
Just figured out this is due to Responsive 2.0 not handling colspan in the header or footer as per #59 .  My jsFiddle example works fine without the colspan footer. http://jsfiddle.net/uonhekd8/4/

**Comment by djuba** [comment]
FYI, placing a `$(window).trigger('resize')` call within the `initComplete` option does not adjust the responsive column widths.  However, running that trigger call through the browser console after the page loads does adjust the responsive column widths and lines the columns up correctly.  I'm at a loss as to why the trigger within the `initComplete` does not work.

**Comment by djuba** [comment]
Just saw this issue was fixed by commit 82e62b3

**Comment by CoralSilver** [comment]
Thanks for posting.  Fix worked for me.
