### ISSUE TITLE
Transparency rows when using with Scroller

### ISSUE THREAD

**Issue by MacTwister** [DataTables/Responsive#67]
I thought better to write here as Scroller works fine on its own. However if I also enable Responsive, then when I click on a row to expand the hidden columns, there is a some styling issue. Our client does not want to have paging and rather scroll. But with 4 tables in tabs and 1000 rows each, I feels its a bit sluggish when just using scrollY. So thats why thought Scroller would be nice add on.

Hope this fiddle helps: http://jsfiddle.net/8u82ry6r/
If you open one row you see alternate rows transperancy. And you hover your mouse over you see a transparency. If you open a 2nd one at the same time you see transparency on rows go away. It seems to depend no which row I click in the striped rows.

Oh I am using Bootstrap with striped table styling.

**Comment by DataTables** [comment]
You have to use a modal display if you want to use Responsive and Scroller. The way Scroller works is that all rows must have equal height, so it can do its virtual calculations. If an extra element (the child row) is injected, the calculations will be completely wrong.

[Bootstrap modal example](http://datatables.net/extensions/responsive/examples/display-types/bootstrap-modal.html)
