### ISSUE TITLE
data-priority not working

### ISSUE THREAD

**Issue by t0n1zz** [DataTables/Responsive#72]
so i tried to add 
```html
<th data-priority="1"> Delete </th>
 ```
but it just not working but if i using javascript way i 
```javascript
$('#myTable').DataTable( {
    responsive: true,
    columnDefs: [
        { responsivePriority: 1, targets: 0 },
        { responsivePriority: 2, targets: -1 }
    ]
} );
```
still work, so where is i'm wrong?

**Comment by DataTables** [comment]
See #57. This unfortunately is a bug in the 2.0.0 release. It has been fixed with the latest code in this repo and I plan to release it in the next week or two.
