### ISSUE TITLE
Distributables (css) not included with the bower package.

### ISSUE THREAD

**Issue by synthecypher** [DataTables/Responsive#73]
Just installed this plugin using bower. `bower install datatables-responsive --save` but there are no `*.css` files included making the bower package useless.

Could you please either publish this project with a `dist` folder including the `*.css` files?

If you're against that then you could please create a separate repository to publish a bower package including the necessary files.

🚀

**Comment by DataTables** [comment]
Hi,

There is a [blog post here](http://datatables.net/blog/2015-11-09) which details how DataTables can be used with bower. `datatables.net-responsive` is the package you want plus a styling package.

The `datatables-responsive` package contains just the source files - which is intentional.
