### ISSUE TITLE
Resizing event when the modal is open

### ISSUE THREAD

**Issue by StephaneHeav** [DataTables/Responsive#74]
I will use this page for example : https://datatables.net/extensions/responsive/examples/display-types/modal.html

When the modal is display :
![start](https://cloud.githubusercontent.com/assets/4067239/12048868/c20c5ef2-aee0-11e5-8516-4d673cc2b9bc.png)

On resize:
-  _resize() call this._redrawChildren() [here](https://github.com/DataTables/Responsive/blob/master/js/dataTables.responsive.js#L736)
- _redrawChildren() call that._detailsDisplay() for each row [here](https://github.com/DataTables/Responsive/blob/master/js/dataTables.responsive.js#L678)

The problem occured only for modal display : it will change the modal data for the last row in the datatable :
![end](https://cloud.githubusercontent.com/assets/4067239/12048870/c4382c74-aee0-11e5-9585-20a118868d38.png)

I tried to filter the correct row in _redrawChildren() but it will only work for modal and break childRow display.

**Comment by DataTables** [comment]
Thanks for letting me know about this!
