### ISSUE TITLE
Responsive tbody mousedown.dtr event prevents select option dropdown within datatable tbody

### ISSUE THREAD

**Issue by djuba** [DataTables/Responsive#76]
In http://jsfiddle.net/myu7vbtf/1/, the select box in Column 1 Row 1 does not show the dropdown options when clicked.  If you uncomment the bottom javascript line and run you can then click on the select box  and see the dropdown options.  This issue is due to the e.preventDefault() in the responsive._detailsInit .on('mousedown.dtr') handler.

**Comment by DataTables** [comment]
This has already been resolved by #68. See http://jsfiddle.net/myu7vbtf/2/ . You would need a `stopPropagation` on click for your select for it to not activate the child row.
