### ISSUE TITLE
Priority doesn't work for me

### ISSUE THREAD

**Issue by CsFender** [DataTables/Responsive#77]
Hi!

I use this solution, what's wrong? Thanks!

            try {
                $('[data-component="dataTable"]')
                    .addClass('display nowrap responsive')
                    .attr('width', '100%')
                    .find('thead th:last-child').attr('data-priority', 1)
                    .end()
                    .DataTable({
                        language: {
                            url: _BASE_HREF + '_js/lib/jquery/plugins/datatables/i18n/' + _BASE_LANG + ".json"
                        },
                        responsive: true
                    });
            }catch (err)
            {
                console.error('dataTables error:', err);
            }

**Comment by DataTables** [comment]
Please link to a test case showing the issue.

**Comment by CsFender** [comment]
Huhh, it's local problem... Sorry!
