### ISSUE TITLE
column-visibility event not firing

### ISSUE THREAD

**Issue by levenegr** [DataTables/Responsive#78]
[Fiddle](https://jsfiddle.net/oavzehfn/)
[Event](https://datatables.net/reference/event/column-visibility)

Pretty self explanatory- the event is firing on 1.0.7, and isn't on 2.0.1.

**Comment by DataTables** [comment]
The major change for v2 (and why it got a v2 version bump) is that Responsive no longer uses DataTables own column visibility controls, but rather now implements its own. The corresponding event is now [`responsive-resize`](http://datatables.net/reference/event/responsive-resize).
