### ISSUE TITLE
Potential Memory leak caused by Responsive Plugin

### ISSUE THREAD

**Issue by pavanpodila** [DataTables/Responsive#82]
The responsive plugin uses the `destroy.dtr` event string to subscribe to destroy events fired by the DataTable. However the DataTable is firing it under the `destroy.dt` namespace. Note the `.dt` instead of `.dtr`. This has resulted in memory leaks in my app as the destroy handler in the Responsive plugin never gets called.

Relevant code from the plugin: https://github.com/DataTables/Responsive/blob/master/js/dataTables.responsive.js#L179-L191

**Comment by DataTables** [comment]
The [DataTables `on` method](http://datatables.net/reference/api/on()) will automatically at the `.dt` event namespace if it isn't present. For example: http://live.datatables.net/risewuti/1/edit .

So it sounds like there is something else happening here. I've just tested Responsive and its event handler does get called.

Can you link to a page showing the error please.

**Comment by pavanpodila** [comment]
Thanks for the quick response. It is good to know that the events are getting called. However when I put a breakpoint in [datatables.responsive code](https://github.com/DataTables/Responsive/blob/master/js/dataTables.responsive.js#L181) , it never gets hit.

**Comment by DataTables** [comment]
Can you link to a page showing the issue please.

**Comment by DataTables** [comment]
Going to close this issue as I've not been able to reproduce it and haven't had a test case showing the issue. If it is still causing issues, please reopen with a test case.

**Comment by lucasA-remora** [comment]
I have run into the same issue where destroy never gets hit within the responsive code, and then the responsive leaks after I switch views and load in a new datatable that is also using the responsive plugin. I can't exactly post a link to the project I am working on, but I will try to replicate this issue in an example project.

**Comment by DataTables** [comment]
That would be great, yes please. I would need a page showing the issue to be able to debug it.
