### ISSUE TITLE
Ability to customize the resposive collapse button

### ISSUE THREAD

**Issue by Kiruwagaka** [DataTables/Responsive#83]
I don't want that pseudo element button i want the ability to simply add my own button or something among those line, that pseudo element destroys the design of my website, is it possible without extensive code modification on my part or on a future release?

**Comment by DataTables** [comment]
Use the `column` option for the `responsive.details.type` option to specify what column you want Responsive to listen for an event on. That column can contain anything you want. In [this example](http://datatables.net/extensions/responsive/examples/child-rows/column-control.html) it uses the pseudo element, but it needn't do that - just put whatever HTML you want into it.
