### ISSUE TITLE
Destroy instead of hide modal?

### ISSUE THREAD

**Issue by kevinmickey** [DataTables/Responsive#84]
Using bootstrap, and a modal for the details view, it looks like a new modal is created, and then hidden, each time a details view is requested.  This could leave a lot of inactive DOM elements.  It seems like it would be better either to destroy instead of hiding the modal, or to check for an existing modal and replace its content.  (Note that bootstrap allows only one modal at a time.)

**Comment by DataTables** [comment]
That makes a lot of sense - thanks! I'll make the required changes for the next release.

**Comment by DataTables** [comment]
Fixed in 3262ee9. Will be int he next release :-)
