### ISSUE TITLE
Column Detail Type Issue

### ISSUE THREAD

**Issue by LittleFej** [DataTables/Responsive#85]
http://jsfiddle.net/f78uzds0/

Bootstrap 3.3.5, DataTables 1.10.11, FixedHeader 3.1.1, Responsive 2.0.2

This issue is a bit of a follow-up to Issue #63.  While the resolution to Issue #63 fixed clicking on a row with no collapsed columns to expose an empty child row, there is still a small issue.

If you have a DataTable with column detail type and you (1) start with a window small enough to have a collapsed column, then (2) click to expand/show the hidden data and then (3) resize the window so that no collapsed columns exist - it will still show an empty child row.

**Comment by DataTables** [comment]
Thanks very much for letting me know about this issue. 95bafcb will resolve it. I expect to do a round of releases next week which will include this change.

**Comment by LittleFej** [comment]
Wonderful.  This is such a great tool.  Thanks for sharing it with the world!
