### ISSUE TITLE
Bower package is not built

### ISSUE THREAD

**Issue by tinchou** [DataTables/Responsive#86]
Hi guys,

I just updated your package and noticed you're now using SCSS instead of CSS. Since this change, I can no longer include the files directly from the `bower_components` folder and I also have to add manual steps to compile these sources.

I'm not a bower expert, but it looks like people tend to distribute the *compiled* version in bower, like [Angular](https://github.com/angular/bower-angular).

Do you think it's a possibility that you distribute the compiled files through bower?

Thanks!

**Comment by DataTables** [comment]
Distribution packages for bower are provided as [documented here](https://datatables.net/download/bower).

**Comment by tinchou** [comment]
Should've looked it up better. Thanks for the quick reply!
