### ISSUE TITLE
Responsive being ignored by Microsoft Edge

### ISSUE THREAD

**Issue by tanis2000** [DataTables/Responsive#87]
It looks like Microsoft Edge is completely ignoring this plugin. 
There's no error shown, but the table isn't resizing, while it works correctly on all other browsers.
If there's any information that I can give you to find out where the problem lies, please ask!

**Comment by DataTables** [comment]
[This example](https://datatables.net/extensions/responsive/examples/initialisation/className.html) appears to work just fine in Edge for me. Does it work for you?
