### ISSUE TITLE
Bootstrap Drop down menu bug in DataTable

### ISSUE THREAD

**Issue by aligoren** [DataTables/Responsive#95]
I get an error in DataTable responsive cell. When I expand opening automatically and sub links are not clickable. I marked black area.

![screenshot_1](https://cloud.githubusercontent.com/assets/4205423/21928311/cc3ac110-d992-11e6-8033-1257006cf13d.png)

**Comment by DataTables** [comment]
Thanks for your question. Could you post support requests in the DataTables forums, as requested in the new issue template text please. Please be sure to include a link to a test case showing the issue.

**Comment by AllanJard** [comment]
Most likely this is due to event listeners not being on the cloned element. The `listHiddenNodes` renderer resolves that. The new rendered is officially supported as of Responsive 3, which should ship in the next month or two.
